name: rec_book
description: "A new Flutter project"
version: 1.0.0+1

environment:
  sdk: '>=3.14.0-0.2.pre <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker: ^0.8.4 
  tflite: ^2.0.0 

flutter:
  uses-material-design: true
